def BuildBadge = addEmbeddableBadgeConfiguration(id: "build", subject: "Build")
def TestBadge = addEmbeddableBadgeConfiguration(id: "test", subject: "Test")

pipeline {
    options {
    // the variable $WORKSPACE is assigned dynamically at the beginning of every stage
    // and might change depending on the number of concurrent builds active.
    // We can only allow 1 concurrent build to have a consistent access to $WORKSPACE
    // Otherwise we should use stash/unstash for the miniconda installation
        disableConcurrentBuilds()
    }
    environment {
       EMAIL_TO_1 = 'victoria.cherkas@meteoswiss.ch'
       EMAIL_TO_2 = 'annika.lauber@c2sm.ethz.ch'
       CONDA_ENV_NAME = 'iconvis'
    }
    agent none
    stages {
        stage('Setup') {
            matrix {
                agent { label "$NODE_NAME}" }
                axes {
                    axis {
                        name 'NODE_NAME'
                        values 'tsa', 'daint'
                    }
                }
                post {
                    failure {
                        script {
                            BuildBadge.setStatus('failing')
                        }
                    }
                    success {
                        script {
                            BuildBadge.setStatus('passing')
                        }
                    }
                }
                stages {
                    stage('setup miniconda') {
                        environment {
                            PATH = "$WORKSPACE/miniconda_$NODE_NAME/bin:$PATH"
                        }
                        steps {
                            script {
                                BuildBadge.setStatus('running')
                            }
                            sh 'testsuite/setup.sh'
                        }
                        post {
                            failure {
                                echo 'Cleaning up workspace'
                                deleteDir()
                            }
                        }
                    }
                }
            }
        }
        stage('Test') {
            matrix {
                agent { label "$NODE_NAME}" }
                axes {
                    axis {
                        name 'NODE_NAME'
                        values 'tsa', 'daint'
                    }
                }
                post {
                    failure {
                        script {
                            TestBadge.setStatus('failing')
                        }
                    }
                    success {
                        script {
                            TestBadge.setStatus('passing')
                        }
                    }
                    always {
                        archiveArtifacts artifacts: '*.log', allowEmptyArchive: true
                        echo 'Cleaning up workspace'
                        deleteDir()
                    }
                }
                stages {
                    stage('run tests') {
                        environment {
                            PATH = "$WORKSPACE/miniconda_${NODE_NAME}/bin:$PATH"
                        }
                        steps {
                            script {
                                TestBadge.setStatus('running')
                            }
                            sh 'testsuite/test.sh'
                        }
                        post {
                            success {
                                mail bcc: '',
                                body: "<b>Jenkins Success</b><br>Project: ${env.JOB_NAME}<br>Build Number: ${env.BUILD_NUMBER}<br>Build URL: ${env.BUILD_URL}" ,
                                cc: "${EMAIL_TO_2}", charset: 'UTF-8', from: '', mimeType: 'text/html',
                                replyTo: '', subject: "Jenkins Job Success ${NODE_NAME} ->${env.JOB_NAME}",
                                to: "${EMAIL_TO_1}";
                            }
                            failure {
                                script {
                                    mail bcc: '',
                                    body: "<b>Jenkins Failure</b><br>Project: ${env.JOB_NAME}<br>Build Number: ${env.BUILD_NUMBER}<br>Build URL: ${env.BUILD_URL}" ,
                                    cc: "${EMAIL_TO_2}", charset: 'UTF-8', from: '', mimeType: 'text/html',
                                    replyTo: '', subject: "Jenkins Job Failure ${NODE_NAME} -> ${env.JOB_NAME}",
                                    to: "${EMAIL_TO_1}";
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
