channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.16
  - git=2.34.1
  - pip
  - cfgrib=0.9.10.4
  - eccodes=2.25.0
  - numpy=1.25.2
  - xarray=2023.8.0
  - pytest=7.4.2
  - psy-reg=1.4.0
  - psy-maps=1.4.2
  - cartopy=0.22.0
  - matplotlib=3.7.2
  - ipympl=0.9.3
  - cmcrameri=1.7
  - jupyter=1.0.0
  - pyinterp=2023.5.0
  - pip:
    - git+https://github.com/psyplot/psy-transect#egg=psy-transect
    - iconarray==0.3.2
  - pre-commit=3.4.0
