channels:
- conda-forge
- defaults
dependencies:
- python=3.9.7
- git=2.34.1
- pip
- cfgrib>=0.9.9.1
- eccodes=2.24.2
- psy-reg
- psy-maps
- cartopy
- psy-view
- numpy
- matplotlib[version='<3.5']
- geos
- proj
- xarray[version='<2022.6.0']
- jupyter
- ipympl
- cmcrameri
- ipython
- netcdf4
- pyinterp
- pytest
- pip:
  - git+https://github.com/psyplot/psy-transect#egg=psy-transect
  - git+https://github.com/C2SM/iconarray@0.2.1
