channels:
- conda-forge
- defaults
dependencies:
- python=3.9.14
- git=2.34.1
- pip
- cfgrib>=0.9.9.1
- eccodes=2.25.0
- numpy
- xarray
- pytest
- psy-view
- psy-reg
- psy-maps
- cartopy
- geos
- proj
- matplotlib
- ipympl
- cmcrameri
- jupyter
- pip:
  - git+https://github.com/psyplot/psy-transect#egg=psy-transect
  - iconarray==0.3.2
- pre-commit