channels:
- conda-forge
- defaults
dependencies:
- python=3.9.14
- git=2.34.1
- pip
- cfgrib>=0.9.9.1
- eccodes=2.25.0
- psy-reg
- psy-maps
- cartopy
- psy-view
- numpy<1.24
- matplotlib[version='<3.5']
- geos
- proj
- xarray
- jupyter
- ipympl
- cmcrameri
- ipython
- netcdf4
- pyinterp
- pytest
- pip:
  - git+https://github.com/psyplot/psy-transect@fix-ufuncs#egg=psy-transect
  - iconarray==0.3.2
- pre-commit
