channels:
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- alsa-lib=1.2.8
- anyio=4.0.0
- argon2-cffi=23.1.0
- argon2-cffi-bindings=21.2.0
- arrow=1.2.3
- asttokens=2.4.0
- async-lru=2.0.4
- attr=2.5.1
- attrs=23.1.0
- aws-c-auth=0.7.0
- aws-c-cal=0.6.0
- aws-c-common=0.8.23
- aws-c-compression=0.2.17
- aws-c-event-stream=0.3.1
- aws-c-http=0.7.11
- aws-c-io=0.13.28
- aws-c-mqtt=0.8.14
- aws-c-s3=0.3.13
- aws-c-sdkutils=0.1.11
- aws-checksums=0.1.16
- aws-crt-cpp=0.20.3
- aws-sdk-cpp=1.10.57
- babel=2.12.1
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.5
- beautifulsoup4=4.12.2
- bleach=6.0.0
- bokeh=3.2.2
- brotli-python=1.0.9
- bzip2=1.0.8
- c-ares=1.19.1
- ca-certificates=2023.7.22
- cached-property=1.5.2
- cached_property=1.5.2
- cairo=1.16.0
- cartopy=0.22.0
- certifi=2023.7.22
- cffi=1.15.1
- cfgrib=0.9.10.4
- cfgv=3.3.1
- cftime=1.6.2
- charset-normalizer=3.2.0
- click=8.1.7
- cloudpickle=2.2.1
- cmcrameri=1.7
- colorama=0.4.6
- comm=0.1.4
- contourpy=1.1.0
- curl=8.1.2
- cycler=0.11.0
- cytoolz=0.12.2
- dask=2023.9.1
- dask-core=2023.9.1
- dbus=1.13.6
- debugpy=1.7.0
- decorator=5.1.1
- defusedxml=0.7.1
- distlib=0.3.7
- distributed=2023.9.1
- docrep=0.3.2
- eccodes=2.25.0
- entrypoints=0.4
- exceptiongroup=1.1.3
- executing=1.2.0
- expat=2.5.0
- fftw=3.3.10
- filelock=3.12.3
- findlibs=0.0.5
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fqdn=1.5.1
- freeglut=3.2.2
- freetype=2.12.1
- fsspec=2023.9.0
- funcargparse=0.2.5
- geos=3.12.0
- gettext=0.21.1
- gflags=2.2.2
- git=2.34.1
- glib=2.74.1
- glib-tools=2.74.1
- glog=0.6.0
- gmp=6.2.1
- graphite2=1.3.13
- gst-plugins-base=1.22.0
- gstreamer=1.22.0
- gstreamer-orc=0.4.34
- harfbuzz=6.0.0
- hdf4=4.2.15
- hdf5=1.12.1
- icu=70.1
- identify=2.5.28
- idna=3.4
- importlib-metadata=6.8.0
- importlib_metadata=6.8.0
- importlib_resources=6.0.1
- iniconfig=2.0.0
- ipykernel=6.25.2
- ipympl=0.9.3
- ipython=8.15.0
- ipython_genutils=0.2.0
- ipywidgets=8.1.0
- isoduration=20.11.0
- jack=1.9.22
- jasper=2.0.33
- jedi=0.19.0
- jinja2=3.1.2
- jpeg=9e
- json5=0.9.14
- jsonpointer=2.0
- jsonschema=4.19.0
- jsonschema-specifications=2023.7.1
- jsonschema-with-format-nongpl=4.19.0
- jupyter=1.0.0
- jupyter-lsp=2.2.0
- jupyter_client=8.3.1
- jupyter_console=6.6.3
- jupyter_core=5.3.1
- jupyter_events=0.7.0
- jupyter_server=2.7.3
- jupyter_server_terminals=0.4.4
- jupyterlab=4.0.5
- jupyterlab_pygments=0.2.2
- jupyterlab_server=2.24.0
- jupyterlab_widgets=3.0.8
- keyutils=1.6.1
- kiwisolver=1.4.5
- krb5=1.20.1
- lame=3.100
- lcms2=2.15
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20230125.3
- libaec=1.0.6
- libarrow=12.0.1
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcap=2.67
- libcblas=3.9.0
- libclang=15.0.7
- libclang13=15.0.7
- libcrc32c=1.1.2
- libcups=2.3.3
- libcurl=8.1.2
- libdb=6.2.32
- libdeflate=1.17
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libexpat=2.5.0
- libffi=3.4.2
- libflac=1.4.3
- libgcc-ng=13.2.0
- libgcrypt=1.10.1
- libgfortran-ng=13.2.0
- libgfortran5=13.2.0
- libglib=2.74.1
- libglu=9.0.0
- libgomp=13.2.0
- libgoogle-cloud=2.12.0
- libgpg-error=1.47
- libgrpc=1.56.2
- libiconv=1.17
- liblapack=3.9.0
- libllvm15=15.0.7
- libnetcdf=4.8.1
- libnghttp2=1.52.0
- libnsl=2.0.0
- libnuma=2.0.16
- libogg=1.3.4
- libopenblas=0.3.24
- libopus=1.3.1
- libpng=1.6.39
- libpq=15.3
- libprotobuf=4.23.3
- libsndfile=1.2.2
- libsodium=1.0.18
- libsqlite=3.43.0
- libssh2=1.11.0
- libstdcxx-ng=13.2.0
- libsystemd0=253
- libthrift=0.18.1
- libtiff=4.5.0
- libtool=2.4.7
- libudev1=253
- libutf8proc=2.8.0
- libuuid=2.38.1
- libvorbis=1.3.7
- libwebp-base=1.3.1
- libxcb=1.13
- libxkbcommon=1.5.0
- libxml2=2.10.3
- libzip=1.10.1
- libzlib=1.2.13
- locket=1.0.0
- lz4=4.3.2
- lz4-c=1.9.4
- markupsafe=2.1.3
- matplotlib=3.4.3
- matplotlib-base=3.4.3
- matplotlib-inline=0.1.6
- mistune=3.0.1
- mpg123=1.31.3
- msgpack-python=1.0.5
- mysql-common=8.0.33
- mysql-libs=8.0.33
- nbclient=0.8.0
- nbconvert=7.8.0
- nbconvert-core=7.8.0
- nbconvert-pandoc=7.8.0
- nbformat=5.9.2
- ncurses=6.4
- nest-asyncio=1.5.6
- netcdf4=1.6.0
- nodeenv=1.8.0
- notebook=7.0.3
- notebook-shim=0.2.3
- nspr=4.35
- nss=3.92
- numpy=1.23.5
- openblas=0.3.24
- openjpeg=2.5.0
- openssl=3.1.2
- orc=1.9.0
- overrides=7.4.0
- packaging=23.1
- pandas=2.1.0
- pandoc=3.1.3
- pandocfilters=1.5.0
- parso=0.8.3
- partd=1.4.0
- patsy=0.5.3
- pcre2=10.37
- perl=5.32.1
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.4.0
- pip=23.2.1
- pixman=0.40.0
- pkgutil-resolve-name=1.3.10
- platformdirs=3.10.0
- pluggy=1.3.0
- ply=3.11
- pooch=1.7.0
- pre-commit=3.4.0
- proj=9.2.1
- prometheus_client=0.17.1
- prompt-toolkit=3.0.39
- prompt_toolkit=3.0.39
- psutil=5.9.5
- psy-maps=1.4.2
- psy-reg=1.4.0
- psy-simple=1.4.1
- psyplot=1.4.3
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulseaudio=16.1
- pulseaudio-client=16.1
- pulseaudio-daemon=16.1
- pure_eval=0.2.2
- pyarrow=12.0.1
- pycparser=2.21
- pygments=2.16.1
- pyinterp=2023.5.0
- pyparsing=3.1.1
- pyproj=3.6.0
- pyqt=5.15.9
- pyqt5-sip=12.12.2
- pyshp=2.3.1
- pysocks=1.7.1
- pytest=7.4.2
- python=3.9.16
- python-dateutil=2.8.2
- python-eccodes=1.4.0
- python-fastjsonschema=2.18.0
- python-json-logger=2.0.7
- python-tzdata=2023.3
- python_abi=3.9
- pytz=2023.3.post1
- pyyaml=6.0.1
- pyzmq=25.1.1
- qt-main=5.15.8
- qtconsole=5.4.4
- qtconsole-base=5.4.4
- qtpy=2.4.0
- rdma-core=28.9
- re2=2023.03.02
- readline=8.2
- referencing=0.30.2
- requests=2.31.0
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rpds-py=0.10.2
- s2n=1.3.46
- scipy=1.11.2
- send2trash=1.8.2
- setuptools=68.1.2
- shapely=2.0.1
- sip=6.7.11
- six=1.16.0
- snappy=1.1.10
- sniffio=1.3.0
- sortedcontainers=2.4.0
- soupsieve=2.5
- sqlite=3.43.0
- stack_data=0.6.2
- statsmodels=0.14.0
- tblib=1.7.0
- terminado=0.17.1
- tinycss2=1.2.1
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- toolz=0.12.0
- tornado=6.3.3
- traitlets=5.9.0
- typing-extensions=4.7.1
- typing_extensions=4.7.1
- typing_utils=0.1.0
- tzdata=2023c
- ucx=1.14.1
- ukkonen=1.0.1
- uri-template=1.3.0
- urllib3=2.0.4
- virtualenv=20.24.4
- wcwidth=0.2.6
- webcolors=1.13
- webencodings=0.5.1
- websocket-client=1.6.3
- wheel=0.41.2
- widgetsnbextension=4.0.8
- xarray=2023.7.0
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xkeyboard-config=2.38
- xorg-fixesproto=5.0
- xorg-inputproto=2.3.2
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.4
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxfixes=5.0.3
- xorg-libxi=1.7.10
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2023.7.0
- xz=5.2.6
- yaml=0.2.5
- zeromq=4.3.4
- zict=3.0.0
- zipp=3.16.2
- zlib=1.2.13
- zstd=1.5.5
- pip:
  - iconarray==0.3.2
  - joblib==1.3.2
  - git+https://github.com/psyplot/psy-transect#egg=psy-transect
  - scikit-learn==1.3.0
  - threadpoolctl==3.2.0
