channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - cfgrib
  - eccodes=2.24.2
  - psy-reg
  - psy-maps
  - cartopy
  - psy-view
  - numpy
  - matplotlib[version='<3.5']
  - geos
  - proj
  - xarray
  - jupyter
  - ipympl
  - cmcrameri
  - ipython
  - netcdf4
  - pyinterp
  - pytest
  - pip:
    - git+https://github.com/psyplot/psy-transect#egg=psy-transect
    - git+https://github.com/C2SM/icon-vis@v0.2.9-alpha#egg=icon-vis