pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label ('tsa || daint')
    }
    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                wget -O ${WORKSPACE}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
                bash miniconda.sh -b -p $WORKSPACE/miniconda
                conda config --set always_yes yes --set changeps1 no
                conda config --add channels conda-forge
                conda env create --name psyplot_${NODE_NAME} --file env/environment.yml
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate psyplot_${NODE_NAME}
                source env/setup-conda-env.sh
                conda deactivate
                rm miniconda.sh
                '''
            }        
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate psyplot_${NODE_NAME}
                python -m cfgrib selfcheck
                pytest testsuite/test*
                '''
            }
        }
    }
}
