pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
       EMAIL_TO = 'victoria.cherkas@meteoswiss.ch'
    }
    agent {
        label ('tsa || daint')
    }
    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
        success {  
            echo 'Successful!'  
        }  
        failure {  
            mail bcc: '', 
            body: "<b>Jenkins Notification</b><br>Project: ${env.JOB_NAME}<br>Build Number: ${env.BUILD_NUMBER}<br>Build URL: ${env.BUILD_URL}", 
            cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', 
            replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", 
            to: "${EMAIL_TO}";  
        }  
    }
    stages {  
        stage('Test') {  
            steps {  
                sh 'echo "Fail!"; exit 1'  
            }  
        }  
    } 
    // stages {
    //     stage('setup miniconda') {
    //         steps {
    //             sh 'wget -O ${WORKSPACE}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
    //             sh 'bash miniconda.sh -b -p $WORKSPACE/miniconda'
    //             sh 'conda config --set always_yes yes --set changeps1 no'
    //             sh 'conda config --add channels conda-forge'
    //             sh 'conda env create --name psyplot_${NODE_NAME} --file env/environment.yml'
    //             sh 'source $WORKSPACE/miniconda/etc/profile.d/conda.sh'
    //             sh 'conda activate psyplot_${NODE_NAME}'
    //             sh 'source env/setup-conda-env.sh'
    //             sh 'conda deactivate'
    //             sh 'rm miniconda.sh'

    //         }        
    //     }
    //     stage('test') {
    //         steps {
    //             sh 'source $WORKSPACE/miniconda/etc/profile.d/conda.sh'
    //             sh 'conda activate psyplot_${NODE_NAME}'
    //             sh 'python -m cfgrib selfcheck'
    //             sh 'pytest testsuite/test*'
    //         }
    //     }
    // }
}
