name: Formatting & compliance

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install $(cat env/environment.yml | grep pre-commit | awk '{print $(NF)}')
        pre-commit install-hooks
    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "GitHub Action: Apply Pep8-formatting"
        git push
    - name: Run checks
      run: |-
        python -m pip list
        pre-commit run --all-files
